apiVersion: ai-resource/v1
kind: Fragment
metadata:
  id: read-file
spec:
  inputs:
    path:
      type: string
      required: true
    focus:
      type: string
  body: "Read {{path}}{{#focus}} and focus on {{focus}}{{/focus}}"
