apiVersion: ai-resource/draft
kind: Prompt
metadata:
  id: implement-feature
  name: Implement Feature
spec:
  fragments:
    read-file:
      inputs:
        path:
          type: string
          required: true
        focus:
          type: string
      body: "Read {{path}}{{#focus}} and focus on {{focus}}{{/focus}}"
    coding-standards:
      body: |
        Follow these coding standards:
        - Write minimal code
        - Add tests only when requested
        - Use descriptive names
  body:
    - fragment: read-file
      inputs:
        path: AGENTS.md
        focus: build system
    - "Review the existing implementation"
    - fragment: coding-standards
    - "Now implement the feature"
