apiVersion: ai-resource/v1
kind: Fragment
metadata:
  id: analyze-files
spec:
  inputs:
    files:
      type: array
      items:
        type: string
      required: true
    focus:
      type: string
  body: |
    Analyze these files:
    {{#files}}
    - {{.}}
    {{/files}}
    {{#focus}}
    Focus on: {{focus}}
    {{/focus}}
