apiVersion: ai-resource/v1
kind: Fragment
metadata:
  id: context-setup
spec:
  body: |
    Consider the following context:
    - Operating system and environment
    - Project structure and dependencies
    - Existing code patterns
