apiVersion: ai-resource/v1
kind: Promptset
metadata:
  id: dev-workflow
  name: Development Workflow
spec:
  prompts:
    implement:
      name: Implement Feature
      body:
        - fragment: read-file
          inputs:
            path: AGENTS.md
        - fragment: coding-standards
        - "Implement the feature"
    
    fix-bug:
      name: Fix Bug
      body:
        - fragment: read-file
          inputs:
            path: AGENTS.md
            focus: error handling
        - "Analyze and fix the bug"
    
    refactor:
      name: Refactor Code
      body:
        - fragment: coding-standards
        - "Refactor the code for clarity"
